### ISSUE TITLE
Vanilla version for this project

### ISSUE THREAD

**Issue by cyclops24** [vsivsi/meteor-job-collection-playground#1]
Hi,
First thanks for your awesome package but I have a small suggestion:

Please provide Vanilla JS version for this demo. Because this is demo example for learning job package usage and maybe someone like me don't understand CoffeeScript and Jade.

Again thanks for your job package

**Comment by vsivsi** [comment]
Hi, sorry, I don't really have time to convert this to a Vanilla JS/HTML/CSS project for you right now.  

Coffeescript is trivial to convert to JS: just use `coffee -c filename.coffee` and it will output a javascript version to `filename.js`  It may not be quite as easy to read as most hand written JS, but it'll do in a pinch.

This was just a little app I wrote to test out the new Later.js functionality I added in v1.1  I decided to share it because I thought others might enjoy it, but it's not really something I plan on maintaining or developing further beyond its present form.
